language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bariyard/react-test -f ./client/Dockerfile.dev ./client
  # can be add other container that need testing

script:
  - docker run -e CI=true bariyard/react-test npm test
  # can be add other container that need testing

after_success:
  - docker build -t bariyard/multi-client ./client
  - docker build -t bariyard/multi-nginx ./nginx
  - docker build -t bariyard/multi-server ./server
  - docker build -t bariyard/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push these image to docker hub
  - docker push bariyard/multi-client
  - docker push bariyard/multi-nginx 
  - docker push bariyard/multi-server
  - docker push bariyard/multi-worker
